python main.py --dataset cifar10 --rate 0.1
python main.py --dataset cifar10 --rate 0.2
python main.py --dataset cifar10 --rate 0.3
python main.py --dataset cifar10 --rate 0.4
python main.py --dataset cifar10 --rate 0.5
python main.py --dataset cifar10 --rate 0.6
python main.py --dataset cifar10 --rate 0.7
python main.py --dataset cifar10 --rate 0.8
python main.py --dataset cifar10 --rate 0.9
python main.py --dataset cifar10 --rate 1.0
python main.py --dataset mnist --rate 0.0
python main.py --dataset mnist --rate 0.1
python main.py --dataset mnist --rate 0.2
python main.py --dataset mnist --rate 0.3
python main.py --dataset mnist --rate 0.4
python main.py --dataset mnist --rate 0.5
python main.py --dataset mnist --rate 0.6
python main.py --dataset mnist --rate 0.7
python main.py --dataset mnist --rate 0.8
python main.py --dataset mnist --rate 0.9
python main.py --dataset mnist --rate 1.0
